### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by IRMobydick** [CaMnter/EasyLikeArea#2]
Hi there
How can add view to `EasyLikeArea` from Right to Left instead of Left to Right?
An of course handle left and right padding of `ImageViews` in correct way

thanks :)

**Comment by CaMnter** [comment]
@IRMobydick I will provide this feature within a few days

**Comment by IRMobydick** [comment]
｡^‿^｡ Thanks ｡^‿^｡
👍 👍 👍
